esphome:
  name: smoker

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
  reboot_timeout: 0s
  
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smoker Fallback Hotspot"
    password: !secret wifi_passwd

captive_portal:

dallas:
  - pin: D2
    update_interval: 5s

web_server:
  port: 80
    
mqtt:
  broker: !secret mqtt_broker
  discovery: True
  id: mqttclient

sensor:
  - platform: dallas
    address: 0xb10000056e870728
    name: "Temperature"
    id: temperature_sensor
  
output:
  - platform: esp8266_pwm
    pin: D1
    id: heater
    inverted: false

button:
  - platform: template
    name: "PID Climate Autotune"
    on_press:
      - climate.pid.autotune: pid_smoker
    
  # Example configuration entry
  # this is not tuned for the smoker
climate:
  - platform: pid
    visual:
      min_temperature: 3
    name: "Smoker heater"
    sensor: temperature_sensor
    id: pid_smoker
    default_target_temperature: 15째C
    heat_output: heater
    control_parameters:
      #kp: 0.1
      #ki: 0.00487
      #kd: 12.56301
      #      kp: 0.0
      #      ki: 0.0
      #      kd: 0.0
      # parameters from autotune
      kp: 0.09701
      ki: 0.00013
      kd: 17.99511
      output_averaging_samples: 5      # smooth the output over 5 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 10 samples
    deadband_parameters:
      threshold_high: 0.5째C       # deadband within +/-0.5째C of target_temperature
      threshold_low: -1째C
      kp_multiplier: 0.05   # proportional gain turned off inside deadband
      ki_multiplier: 0.05  # integral accumulates at only 5% of normal ki
      kd_multiplier: 0.0   # derviative is turned off inside deadband
      deadband_output_averaging_samples: 15   # average the output over 15 samples within the deadband
